version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGODB_URL: ${MONGODB_URL} # ใช้ตัวแปรจาก .env
      JWT_SECRET: ${JWT_SECRET}   # ใช้ตัวแปรจาก .env
    ports:
      - 3001:3000
    depends_on:
      - mongo
