name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t PXTN45/h2o-app .
      - name: Publish image to docker hub
        run: docker push PXTN45/h2o-app:latest
        
  deploy:
    needs: build
    runs-on: aws-ec2 # เปลี่ยนจาก aws-ec2 เป็น ubuntu-latest หรือใช้ runner อื่นตามต้องการ
    steps:
      - name: Pull image from docker hub
        run: docker pull PXTN45/h2o-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container || true # เพิ่ม || true เพื่อไม่ให้ล้มเหลวถ้าไม่มี container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nodejs-app-container PXTN45/h2o-app
=======
        run: docker run -d -p 3000:3000 --name nodejs-app-container PXTN45/h2o-app
>>>>>>> d35a84a172488289d65e94d217dd478a92f250ef
